import { DayData } from '@/types';

export const CSV_URL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRE1LpePw6cB0XBCg-gzVVHVCRmR3ywb5mxiCVKOw8FTRYDBnAk9n0WJ1ocwIhnIdGeuvYJfEj7C4f0/pub?gid=0&single=true&output=csv';

export const INITIAL_DATA: DayData[] = [
  {
    date: '2025-12-26',
    day: 'Day 1',
    day_zh: '第一天',
    dayTitle: 'Arrival in Fukuoka 🛬',
    dayTitle_zh: '抵達福岡 🛬',
    dayHighlight: 'First taste of Hakata!',
    dayHighlight_zh: '初嚐博多美食！',
    dayTips: '💡 Get SUGOCA IC card at airport. Subway to Hakata (5 min, ¥260).',
    dayTips_zh: '💡 在機場買 SUGOCA IC卡，搭地鐵到博多站（5分鐘，¥260）',
    items: [
      {
        time: '13:00',
        activity: 'Arrive at Fukuoka Airport',
        activity_zh: '抵達福岡機場',
        location: 'Fukuoka Airport International Terminal',
        location_zh: '福岡機場國際航廈',
        icon: 'plane',
        link: 'https://www.fukuoka-airport.jp/en/',
        linkLabel: 'Airport Info',
        mapLink: 'https://maps.google.com/?q=Fukuoka+Airport+International+Terminal',
      },
      {
        time: '14:30',
        activity: 'Lunch: Makino Udon',
        activity_zh: '午餐：牧野烏龍麵',
        location: 'Hakata Station KITTE B1F',
        location_zh: '博多站 KITTE B1F',
        icon: 'food',
        link: 'https://tabelog.com/fukuoka/A4001/A400101/40041829/',
        linkLabel: 'Tabelog 3.54★',
        mapLink: 'https://maps.google.com/?q=KITTE+Hakata',
      },
      {
        time: '16:00',
        activity: 'Hotel Check-in & Rest',
        activity_zh: '飯店入住 & 休息',
        location: 'Hotel Near Hakata/Nakasu',
        location_zh: '博多/中洲附近飯店',
        icon: 'hotel',
      },
      {
        time: '18:30',
        activity: 'Dinner: Motsunabe Ichifuji',
        activity_zh: '晚餐：もつ鍋一藤（牛腸鍋）',
        location: 'Nakasu Area',
        location_zh: '中洲區',
        icon: 'food',
        link: 'https://tabelog.com/fukuoka/A4001/A400102/40000508/',
        linkLabel: 'Tabelog 3.72★',
        mapLink: 'https://maps.google.com/?q=もつ鍋一藤+福岡',
      },
      {
        time: '21:00',
        activity: 'Nakasu Yatai Stroll',
        activity_zh: '中洲屋台散步',
        location: 'Nakasu Riverside',
        location_zh: '中洲河畔',
        icon: 'walk',
        link: 'https://yokanavi.com/en/yatai/',
        linkLabel: 'Yatai Guide',
        mapLink: 'https://maps.google.com/?q=Nakasu+Yatai+Fukuoka',
      },
    ],
  },
  {
    date: '2025-12-27',
    day: 'Day 2',
    day_zh: '第二天',
    dayTitle: 'Kumamoto Adventure 🏯',
    dayTitle_zh: '熊本探險 🏯',
    dayHighlight: 'Castle & horse meat!',
    dayHighlight_zh: '城堡 & 馬肉料理！',
    dayTips: '💡 Shinkansen: Hakata→Kumamoto (33 min, ¥5,130). Taxi to castle.',
    dayTips_zh: '💡 新幹線：博多→熊本（33分鐘，¥5,130），搭計程車到城堡',
    items: [
      {
        time: '09:00',
        activity: 'Shinkansen to Kumamoto',
        activity_zh: '搭新幹線前往熊本',
        location: 'Hakata Station → Kumamoto Station',
        location_zh: '博多站 → 熊本站',
        icon: 'train',
        link: 'https://www.jrkyushu.co.jp/english/',
        linkLabel: 'JR Kyushu',
        mapLink: 'https://maps.google.com/?q=Hakata+Station',
      },
      {
        time: '10:00',
        activity: 'Drop bags at hotel',
        activity_zh: '寄放行李到飯店',
        location: 'Kumamoto Station Area',
        location_zh: '熊本站周邊',
        icon: 'hotel',
        mapLink: 'https://maps.google.com/?q=Kumamoto+Station',
      },
      {
        time: '12:00',
        activity: 'Lunch: Katsuretsu Tei (Pork Cutlet)',
        activity_zh: '午餐：勝烈亭（炸豬排）',
        location: 'Shimotori Arcade',
        location_zh: '下通商店街',
        icon: 'food',
        link: 'https://tabelog.com/kumamoto/A4301/A430101/43000092/',
        linkLabel: 'Tabelog 3.65★',
        mapLink: 'https://maps.google.com/?q=勝烈亭+熊本+下通',
      },
      {
        time: '14:00',
        activity: 'Kumamoto Castle',
        activity_zh: '熊本城',
        location: 'Kumamoto Castle Area',
        location_zh: '熊本城區域',
        icon: 'castle',
        link: 'https://castle.kumamoto-guide.jp/en/',
        linkLabel: 'Castle Info',
        mapLink: 'https://maps.google.com/?q=Kumamoto+Castle',
      },
      {
        time: '18:30',
        activity: 'Dinner: Suganoya (Horse Meat)',
        activity_zh: '晚餐：菅乃屋（馬刺身）',
        location: 'Shimotori Area',
        location_zh: '下通區域',
        icon: 'food',
        link: 'https://tabelog.com/kumamoto/A4301/A430101/43000028/',
        linkLabel: 'Tabelog 3.58★',
        mapLink: 'https://maps.google.com/?q=菅乃屋+熊本',
      },
      {
        time: '21:00',
        activity: 'Rest at hotel',
        activity_zh: '回飯店休息',
        location: 'Kumamoto Hotel',
        location_zh: '熊本飯店',
        icon: 'hotel',
      },
    ],
  },
  {
    date: '2025-12-28',
    day: 'Day 3',
    day_zh: '第三天',
    dayTitle: 'Gardens & Return 🌿',
    dayTitle_zh: '庭園 & 返回福岡 🌿',
    dayHighlight: 'Meet Kumamon!',
    dayHighlight_zh: '見熊本熊！',
    dayTips: '💡 Taxi to Suizenji Garden (10 min). Kumamon Square is FREE!',
    dayTips_zh: '💡 搭計程車到水前寺（10分鐘），熊本熊廣場免費！',
    items: [
      {
        time: '09:30',
        activity: 'Suizenji Garden',
        activity_zh: '水前寺成趣園',
        location: 'Suizenji Park (Taxi 10 min)',
        location_zh: '水前寺公園（計程車10分鐘）',
        icon: 'park',
        link: 'https://www.suizenji.or.jp/',
        linkLabel: 'Garden Info',
        mapLink: 'https://maps.google.com/?q=Suizenji+Jojuen+Garden',
      },
      {
        time: '12:00',
        activity: 'Lunch: Kokutei Ramen',
        activity_zh: '午餐：黒亭拉麵',
        location: 'Near Kumamoto Station',
        location_zh: '熊本站附近',
        icon: 'food',
        link: 'https://tabelog.com/kumamoto/A4301/A430101/43001147/',
        linkLabel: 'Tabelog 3.71★',
        mapLink: 'https://maps.google.com/?q=黒亭+熊本',
      },
      {
        time: '14:00',
        activity: 'Kumamon Square',
        activity_zh: '熊本熊廣場',
        location: 'Tetoria Kumamoto Building 1F',
        location_zh: '鶴屋百貨東館1F',
        icon: 'camera',
        link: 'https://kumamon-sq.jp/',
        linkLabel: 'Kumamon Sq',
        mapLink: 'https://maps.google.com/?q=Kumamon+Square+Kumamoto',
      },
      {
        time: '16:00',
        activity: 'Shinkansen back to Fukuoka',
        activity_zh: '搭新幹線返回福岡',
        location: 'Kumamoto Station → Hakata Station',
        location_zh: '熊本站 → 博多站',
        icon: 'train',
        mapLink: 'https://maps.google.com/?q=Kumamoto+Station',
      },
      {
        time: '19:00',
        activity: 'Dinner: Hanamidori (Chicken Hotpot)',
        activity_zh: '晚餐：華味鳥（雞肉水炊鍋）',
        location: 'Nakasu/Tenjin Area',
        location_zh: '中洲/天神區域',
        icon: 'food',
        link: 'https://tabelog.com/fukuoka/A4001/A400103/40000022/',
        linkLabel: 'Tabelog 3.69★',
        mapLink: 'https://maps.google.com/?q=華味鳥+博多',
      },
    ],
  },
  {
    date: '2025-12-29',
    day: 'Day 4',
    day_zh: '第四天',
    dayTitle: 'Yanagawa Boat 🚣',
    dayTitle_zh: '柳川遊船 🚣',
    dayHighlight: 'Kotatsu boat ride!',
    dayHighlight_zh: '暖桌船超舒服！',
    dayTips: '💡 Nishitetsu train to Yanagawa (50 min). NO EEL → get udon!',
    dayTips_zh: '💡 西鐵電車到柳川（50分鐘），不吃鰻魚 → 改吃烏龍麵！',
    items: [
      {
        time: '09:00',
        activity: 'Nishitetsu train to Yanagawa',
        activity_zh: '搭西鐵電車到柳川',
        location: 'Tenjin Station → Yanagawa',
        location_zh: '天神站 → 柳川',
        icon: 'train',
        link: 'https://www.nishitetsu.jp/en/',
        linkLabel: 'Nishitetsu',
        mapLink: 'https://maps.google.com/?q=Nishitetsu+Fukuoka+Tenjin+Station',
      },
      {
        time: '10:30',
        activity: 'Yanagawa River Cruise (Kotatsu Boat)',
        activity_zh: '柳川遊船（暖桌船）',
        location: 'Yanagawa Boat Pier',
        location_zh: '柳川乘船處',
        icon: 'boat',
        link: 'https://www.yanagawa-net.com/en/',
        linkLabel: 'Boat Info',
        mapLink: 'https://maps.google.com/?q=Yanagawa+River+Boat+Cruise',
      },
      {
        time: '12:30',
        activity: 'Lunch: Tachibana Udon (No Eel!)',
        activity_zh: '午餐：立花烏龍麵（不是鰻魚！）',
        location: 'Yanagawa Town',
        location_zh: '柳川市區',
        icon: 'food',
        link: 'https://tabelog.com/fukuoka/A4008/A400804/40024577/',
        linkLabel: 'Tabelog 3.42★',
        mapLink: 'https://maps.google.com/?q=柳川+うどん',
      },
      {
        time: '15:00',
        activity: 'Dazaifu Tenmangu Shrine',
        activity_zh: '太宰府天滿宮',
        location: 'Dazaifu City',
        location_zh: '太宰府市',
        icon: 'shrine',
        link: 'https://www.dazaifutenmangu.or.jp/en/',
        linkLabel: 'Shrine Info',
        mapLink: 'https://maps.google.com/?q=Dazaifu+Tenmangu+Shrine',
      },
      {
        time: '17:30',
        activity: 'Return to Fukuoka',
        activity_zh: '返回福岡',
        location: 'Dazaifu → Tenjin',
        location_zh: '太宰府 → 天神',
        icon: 'train',
        mapLink: 'https://maps.google.com/?q=Dazaifu+Station',
      },
      {
        time: '19:00',
        activity: 'Dinner: Tenjin Horumon (Yakiniku)',
        activity_zh: '晚餐：天神ホルモン（燒肉）',
        location: 'Tenjin Area',
        location_zh: '天神區域',
        icon: 'food',
        link: 'https://tabelog.com/fukuoka/A4001/A400103/40019737/',
        linkLabel: 'Tabelog 3.52★',
        mapLink: 'https://maps.google.com/?q=天神ホルモン+福岡',
      },
    ],
  },
  {
    date: '2025-12-30',
    day: 'Day 5',
    day_zh: '第五天',
    dayTitle: 'Mojiko Retro 🚂',
    dayTitle_zh: '門司港懷舊 🚂',
    dayHighlight: 'Fresh sushi!',
    dayHighlight_zh: '新鮮壽司！',
    dayTips: '💡 JR to Mojiko (90 min). Karato Market best before 11am!',
    dayTips_zh: '💡 JR到門司港（90分鐘），唐戶市場最好11點前去！',
    items: [
      {
        time: '08:00',
        activity: 'JR train to Kokura, then Mojiko',
        activity_zh: 'JR電車到小倉，再轉門司港',
        location: 'Hakata → Kokura → Mojiko',
        location_zh: '博多 → 小倉 → 門司港',
        icon: 'train',
        mapLink: 'https://maps.google.com/?q=Hakata+Station',
      },
      {
        time: '10:00',
        activity: 'Karato Market (Fresh Sushi)',
        activity_zh: '唐戶市場（新鮮壽司）',
        location: 'Shimonoseki (5 min ferry)',
        location_zh: '下關（渡輪5分鐘）',
        icon: 'food',
        link: 'https://tabelog.com/yamaguchi/A3502/A350201/35000493/',
        linkLabel: 'Tabelog 3.55★',
        mapLink: 'https://maps.google.com/?q=Karato+Market+Shimonoseki',
      },
      {
        time: '12:30',
        activity: 'Mojiko Retro District',
        activity_zh: '門司港懷舊區',
        location: 'Mojiko Port Area',
        location_zh: '門司港區域',
        icon: 'camera',
        link: 'https://www.mojiko.info/en/',
        linkLabel: 'Mojiko Info',
        mapLink: 'https://maps.google.com/?q=Mojiko+Retro',
      },
      {
        time: '14:00',
        activity: 'Mojiko Observation Deck',
        activity_zh: '門司港展望台',
        location: 'Mojiko Retro Highmart',
        location_zh: '門司港懷舊高層大樓',
        icon: 'camera',
        mapLink: 'https://maps.google.com/?q=門司港レトロ展望室',
      },
      {
        time: '17:00',
        activity: 'Return to Fukuoka',
        activity_zh: '返回福岡',
        location: 'Mojiko → Hakata',
        location_zh: '門司港 → 博多',
        icon: 'train',
        mapLink: 'https://maps.google.com/?q=Mojiko+Station',
      },
      {
        time: '19:00',
        activity: 'Dinner: Tetsunabe Gyoza',
        activity_zh: '晚餐：鐵鍋餃子',
        location: 'Hakata Area',
        location_zh: '博多區域',
        icon: 'food',
        link: 'https://tabelog.com/fukuoka/A4001/A400101/40000027/',
        linkLabel: 'Tabelog 3.62★',
        mapLink: 'https://maps.google.com/?q=鉄なべ+博多',
      },
    ],
  },
  {
    date: '2025-12-31',
    day: 'Day 6',
    day_zh: '第六天',
    dayTitle: 'NYE 🎆',
    dayTitle_zh: '跨年夜 🎆',
    dayHighlight: 'Countdown!',
    dayHighlight_zh: '倒數！',
    dayTips: '💡 MUST reserve Nikuichi! Shrine crowded after 23:30.',
    dayTips_zh: '💡 肉一一定要預約！神社23:30後很擠',
    items: [
      {
        time: '10:00',
        activity: 'Canal City Shopping',
        activity_zh: '博多運河城購物',
        location: 'Canal City Hakata',
        location_zh: '博多運河城',
        icon: 'shopping',
        link: 'https://canalcity.co.jp/en',
        linkLabel: 'Canal City',
        mapLink: 'https://maps.google.com/?q=Canal+City+Hakata',
      },
      {
        time: '13:00',
        activity: 'Lunch at Canal City',
        activity_zh: '午餐：運河城',
        location: 'Canal City Food Court',
        location_zh: '運河城美食街',
        icon: 'food',
        mapLink: 'https://maps.google.com/?q=Canal+City+Hakata',
      },
      {
        time: '15:00',
        activity: 'Ohori Park',
        activity_zh: '大濠公園',
        location: 'Ohori Park',
        location_zh: '大濠公園',
        icon: 'park',
        link: 'https://www.ohorikouen.jp/',
        linkLabel: 'Park Info',
        mapLink: 'https://maps.google.com/?q=Ohori+Park+Fukuoka',
      },
      {
        time: '18:00',
        activity: 'Dinner: Nikuichi Wagyu (RESERVED)',
        activity_zh: '晚餐：肉一和牛燒肉（已預約）',
        location: 'Tenjin Area',
        location_zh: '天神區域',
        icon: 'food',
        link: 'https://tabelog.com/fukuoka/A4001/A400103/40041477/',
        linkLabel: 'Tabelog 3.68★',
        mapLink: 'https://maps.google.com/?q=焼肉+肉一+天神',
      },
      {
        time: '21:00',
        activity: 'Rest before countdown',
        activity_zh: '休息準備跨年',
        location: 'Hotel',
        location_zh: '飯店',
        icon: 'hotel',
      },
      {
        time: '23:30',
        activity: 'NYE at Sumiyoshi Shrine',
        activity_zh: '住吉神社跨年',
        location: 'Sumiyoshi Shrine',
        location_zh: '住吉神社',
        icon: 'shrine',
        link: 'https://www.nihon-kankou.or.jp/fukuoka/402010/detail/40201ag2130013670',
        linkLabel: 'Shrine Info',
        mapLink: 'https://maps.google.com/?q=Sumiyoshi+Shrine+Fukuoka',
      },
    ],
  },
  {
    date: '2026-01-01',
    day: 'Day 7',
    day_zh: '第七天',
    dayTitle: 'Fly Home 👋',
    dayTitle_zh: '回家 👋',
    dayHighlight: 'Happy New Year!',
    dayHighlight_zh: '新年快樂！',
    dayTips: '💡 Book taxi night before. 2 hrs before flight.',
    dayTips_zh: '💡 前一晚預約計程車，起飛前2小時到機場',
    items: [
      {
        time: '08:00',
        activity: 'Pack & checkout',
        activity_zh: '打包退房',
        location: 'Hotel',
        location_zh: '飯店',
        icon: 'hotel',
      },
      {
        time: '09:30',
        activity: 'Taxi to Airport',
        activity_zh: '搭計程車到機場',
        location: 'Hotel → Fukuoka Airport',
        location_zh: '飯店 → 福岡機場',
        icon: 'taxi',
        mapLink: 'https://maps.google.com/?q=Fukuoka+Airport',
      },
      {
        time: '10:00',
        activity: 'Airport Check-in & Shopping',
        activity_zh: '報到 & 最後購物',
        location: 'Fukuoka Airport International',
        location_zh: '福岡機場國際航廈',
        icon: 'shopping',
        mapLink: 'https://maps.google.com/?q=Fukuoka+Airport+International+Terminal',
      },
      {
        time: '12:00',
        activity: 'Flight to Hong Kong',
        activity_zh: '飛回香港',
        location: 'Fukuoka → Hong Kong',
        location_zh: '福岡 → 香港',
        icon: 'plane',
        link: 'https://www.fukuoka-airport.jp/en/',
        linkLabel: 'Airport Info',
        mapLink: 'https://maps.google.com/?q=Fukuoka+Airport',
      },
    ],
  },
];
